config/routes.rb
Rails.application.routes.draw do


  resources :teams do
    resources :okrs
end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/okr.rb
class Okr < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :okrs, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  

end

app/controllers/okrs_controller.rb
class OkrsController < ApplicationController
  before_action :set_team
  before_action :set_okr, only: [:show, :edit, :update, :destroy]

  # GET /okrs
  # GET /okrs.json
  def index
    @okrs = Okr.all
  end

  # GET /okrs/1
  # GET /okrs/1.json
  def show

  end

  # GET /okrs/new
  def new
    @team = Team.find(params[:team_id])
    @okr = Okr.new
  end

  # GET /okrs/1/edit
  def edit
    @team = Team.find(params[:team_id])

  end

  # POST /okrs
  # POST /okrs.json
  def create
    @team = Team.find(params[:team_id])
    @okr = Okr.new(okr_params)

      if @okr.save
          #flash[:sucess] = "Sucesso!"
          redirect_to action: "show", id: @okr.id
        #format.html { redirect_to @okr, notice: 'Okr was successfully created.' }
        #format.json { render :show, status: :created, location: @okr }
      else
        flash[:error] = @okr.error.full_messages
        redirect_to action: "new", id: @okr.id

        #format.html { render :new }
        #format.json { render json: @okr.errors, status: :unprocessable_entity }
      end

  end

  # PATCH/PUT /okrs/1
  # PATCH/PUT /okrs/1.json
  def update

      if @okr.update(okr_params)

          redirect_to action: "show", id: @okr.id, notice: "A Okr foi editado com sucesso!"
        #format.html { redirect_to @okr, notice: 'Okr was successfully updated.' }
        #format.json { render :show, status: :ok, location: @okr }
      else

        #format.html { render :edit }
        #format.json { render json: @okr.errors, status: :unprocessable_entity }

      end
  end

  # DELETE /okrs/1
  # DELETE /okrs/1.json
  def destroy

    @okr.destroy
    redirect_to team_okrs_path(@team)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
     def set_team
      @team = Team.find(params[:team_id])
    end

    def set_okr
      @okr = Okr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def okr_params
      params.require(:okr).permit(:title, :description, :team_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index  	
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/okrs_helper.rb
module OkrsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ink</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="application.css.scss">

<style>
.footer{
  height: 19px;
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  padding: 0;
  position: fixed;

}



</style>

  </head>


  <body style="background-color:#f2f2f2">
  <font style = "font-family:verdana", color = 'purple'>

  <div align="left"> <%= image_tag("logo/logo.png", width: "150px") %> </div>
<div id="wrapper" class="clearfix">
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
             <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button> <a class="navbar-brand" href="/">Inkflow</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Equipes", teams_path %>
            </li>
            <li>
              <a href="#">Link</a>
            </li>

          </ul>
          <%if user_signed_in?%>
          <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.email%><strong class="caret"></strong></a>
              <ul class="dropdown-menu">

                <%if current_user.admin%>
                <li>
                  <%= link_to 'Admin', rails_admin_path %>
                <li>
                <%end%>

                <li>
                  <%= link_to 'Editar', edit_user_registration_path, method: :get %>
                <li>
                  <%= link_to 'Cancelar Conta', edit_user_registration_path, method: :delete, data: { confirm: 'Tem certeza?' } %>
                </li>
                <li class="divider">
                </li>
                <li>
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete, data: { confirm: 'Tem certeza?' } %>
                </li>
              </ul>
            </li>

          <%end%>

          </ul>
        </div>

      </nav>
    </div>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
</div>



  <div class="footer" align="center">
      <p>&copy; Inkflow 2016, All rights reserved</p>
  </div>
  </div> <!-- END OF WRAPPER -->
  </body>
</html>

app/views/okrs/_form.html.erb
<%= form_for(okr) do |f| %>
  <% if okr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(okr.errors.count, "error") %> prohibited this okr from being saved:</h2>

      <ul>
      <% okr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.text_field :team_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/okrs/edit.html.erb
<h1>Editing Okr</h1>

<%= form_for([@team, @okr]) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.text_field :team_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', team_okrs_path %>

app/views/okrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Okrs</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Equipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team.okrs.each do |okr| %>
      <tr>
        <td><%= okr.title %></td>
        <td><%= okr.description %></td>
        <td><%= @team.title %></td>
        <td><%= link_to 'Mostrar', {:action => 'show', :id => okr.id} %></td>
        <td><%= link_to 'Editar', {:action => 'edit', :id => okr.id} %></td>
        <td><%= link_to 'Excluir', {:action => 'destroy', :id => okr.id}, method: :delete, data: { confirm: 'Tem certeza' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Okr', new_team_okr_path(@team) %>

app/views/okrs/new.html.erb
<h1>New Okr</h1>

<%= form_for([@team, @team.okrs.build]) do |f| %>
 <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.text_field :team_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', team_okrs_path %>

app/views/okrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @okr.title %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @okr.description %>
</p>

<p>
  <strong>Equipe:</strong>
  <%= @team.title %>
</p>

<%= link_to 'Editar', edit_team_okr_path(@okr) %> |
<%= link_to 'Voltar', team_okrs_path %>

app/views/welcome/index.html.erb
<style>
h3 {
  size: 22;
  
}
</style>

<div align="left">
	<h3>
	<strong>
	Bem Vindo ao Inkflow, <em>logado como: <%=current_user.email%></em>
	</strong>
	</h3>

</div>
<br><br>

<div class="container">

	<p class="text-muted lead">
			O projeto de uma Aplicação Web que veio para sanar o problema do NTI (Núcleo de Tecnologia da Informação). NTI adotou a metodologia OKR em seus projetos, e vêm enfrentando uma série de dificuldades pricipalmente no queito visualização.

			Inkflow soluciona esses problemas com uma interface leve e simples de ser utilizada.
	</p>
</div>